---
- hosts: localhost
  become: true
  become_user: root
  become_method: su
  gather_facts: true
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes state=latest
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted 
